### PR TITLE
add: brssug group info

### PR DESCRIPTION
**Pull request by colinwilliams91**
made this branch on a chrome book with 4gb of ram running a linux VM so i literally couldnt even spin up localhost to check if this stuff worked. 

if someone could checkout the branch and spin it, my guess is it should be fine...

### CODE REVIEW

**Review by codingMustache — APPROVED** [review]

**Review by Aeshus — APPROVED** [review]

**Comment by colinwilliams91** [comment]
@Aeshus @codingMustache 
i know this PR is small but did anyone checkout the branch and spin it up? the laptop i am using can't even view localhost lol...

and there are things i would have loved to have checked on localhost..

**Comment by Aeshus** [comment]
I spun it up locally and it worked.

**Comment by colinwilliams91** [comment]
> I spun it up locally and it worked.

great, thank you.

**Comment by codingMustache** [comment]
Same

**Pull request merged**
