### PR TITLE
Styles on Home Page done

### PR DESCRIPTION
**Pull request by codingMustache**

### CODE REVIEW

**Review by colinwilliams91 — CHANGES_REQUESTED** [review]
I liked the Card centered like this: 
image

**Comment by colinwilliams91** [comment]
Can't see the Logo with Dark mode: 
image

**Comment by colinwilliams91** [comment]
Responsive "Brand" Logo in Nav is awesome ✔️ 
Card Shadow Light Mode ✔️

**Comment by codingMustache** [comment]
> Can't see the Logo with Dark mode: image

Dark mode Feat isnt done yet one it is, I plan on swapping the picture

**Review by colinwilliams91 — APPROVED** [review]

**Pull request merged**
