### PR TITLE
feat: Add Github and Discord to homepage

### PR DESCRIPTION
**Pull request by Aeshus**
I added the links to the card following the code in `app/[slug]/page.tsx`. Copied the `Divider` and `CardFooter` parts, and used the Link elements to point to the pages (for some reason <a> is also used in `app/[slug]/page.tsx`?).

I used the same icon repository (ant-icons) to choose the icons. The Github icon is self-explanatory, while the Message icon was chosen because there isn't a Discord icon in the icon repository.

Icons were chosen over the full URL as the default footer styling makes it an ugly two-column layout and has text-wrapping. As such, I just opted to use the icons (and made them large) to save the headache of restyling. Could also just change to the names of the service (ex. "Github" and "Discord).

### CODE REVIEW

**Review by colinwilliams91 — APPROVED** [review]
@Aeshus love it!! Thank you :smile:

Maybe we can use that message bubble as a placeholder for the discord icon soon.

**Comment by colinwilliams91** [comment]
needs linting but im about to make a small change to the organizers object and idk if you have the `eslintrc.json` yet, so ill just make those changes 😛

**Comment by Aeshus** [comment]
I think Prettier is fighting eslint on what is allowed and what isn't...

Mmm, I love modern tooling!

**Comment by Aeshus** [comment]
All of the ESLint stuff has been fixed (thanks, prettier) and I fixed any conflicts with main. I'ma merge now.

**Pull request merged**
